# ---- Stage 1: get uv image ----
FROM ghcr.io/astral-sh/uv:trixie-slim@sha256:5cbec7ab7753a6c763c6dda6a38f085c8c585ec9f53cfb4e7368b79ca30bc881 AS uv

# ---- Stage 2: main image ----
FROM debian:trixie-slim@sha256:e18da95f66066b7c5fa31491b524e83121271eca59a3d140f4906c8d0a090367

ENV DEBIAN_FRONTEND=noninteractive

# System + scientific dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    build-essential \
    pkg-config \
    libnetcdf-dev \
    netcdf-bin \
    libhdf5-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    cdo \
    nco \
    python3.13 \
    python3.13-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Make `python` command available
RUN ln -s /usr/bin/python3.13 /usr/bin/python

# Copy uv from official image
COPY --from=uv /uv /usr/local/bin/uv

# Working directory
WORKDIR /workspace

CMD ["/bin/bash"]